added tf files

diff --git a/.github/workflows/checks-fmt.yml b/.github/workflows/checks-fmt.yml
--- a/.github/workflows/checks-fmt.yml
+++ b/.github/workflows/checks-fmt.yml
@@ -40,19 +40,30 @@ jobs:
         run: |
           # Initialize an empty variable to store results
           failed_files=""
+          
+          # Prevent the script from exiting on non-zero exit codes
+          set +e
+
           # Check each changed .tf file
           git diff --name-only origin/${{ github.base_ref }} -- | grep '\.tf$' | while IFS= read -r file; do
-            if ! terraform fmt -check "$file" || true; then
+            terraform fmt -check "$file"
+            exit_code=$?
+            if [ $exit_code -eq 1 ]; then
+              echo "Error checking file: $file"
+              exit 1
+            elif [ $exit_code -eq 2 ]; then
               failed_files="$failed_files\n❌ \`$file\` is not properly formatted. Please run \`terraform fmt $file\` to fix it."
             fi
           done
+
           # Save failed files list to a file for use in the next step
-          echo "$failed_files" > fmt-output.txt
-          # Set output for use in the next step, removing any newlines from the variable for proper evaluation in 'if' conditions
-          if [ -n "$failed_files" ]; then
-            echo "::set-output name=failed_files::true"
+          echo -e "$failed_files" > fmt-output.txt
+
+          # Set output for use in the next step
+          if [ -s fmt-output.txt ]; then
+            echo "failed_files=true" >> $GITHUB_OUTPUT
           else
-            echo "::set-output name=failed_files::false"
+            echo "failed_files=false" >> $GITHUB_OUTPUT
           fi
 
       # Step 5: Post PR Comment (only if there are failed files)
